### PR TITLE
add Welcome, History, Users, and more

### PR DESCRIPTION
**Pull request by suprenant**
Add: 
 - Welcome
 - History
 - Users and stakeholders
 - Problem being solved
 - Anticipated outcomes
 - Metrics for success
 - Roadmap
 - Risks and mitigations

Remove:
 - Description

Also tweak some Tools copy

### CODE REVIEW

**Review by annahsgraves — APPROVED** [review]
I approve this PR, with the copy edits I made incorporated.

**Comment by annahsgraves** [comment]
@hursey013 since I made additional copy edits, it would be great to nab a review + merge from you. Thanks!

**Review by hursey013 — APPROVED** [review]
Made a few small tweaks, otherwise LGTM

**Comment by suprenant** [comment]
Thanks for the tweaks, @annahsebok @hursey013 ! I'm going ahead and merging.

**Pull request merged**
