### PR TITLE
Update landing page

### PR DESCRIPTION
**Pull request by hursey013**
Iterating on prototype to incorporate changes from @Lapedra's Illustrator mockup.

localhost_4000_ 8

### CODE REVIEW

**Comment by Lapedra** [comment]
There's a typo in the "Keep up to date" section - last sentence (tge).
Remove (/) from "click here" under "Questions" at the bottom.
Remove /a> tag from "Submit a FOIA request."
Can we add more space b/w the three sections in "Get started with the TSP?" Also, can we decrease the padding/margin above "Get started with the TSP?"

**Comment by hursey013** [comment]
Good catch @Lapedra! I don't have Illustrator on my computer so I hand typed out the content, and clearly had some slip-ups. Also adjusted the padding a bit on the elements you mentioned. You can see those changes reflected from my commit in the code here: https://github.com/18F/tsp-uswds/pull/29/commits/f8b33b4ace8593ecca07fcb7640639debe018eaa

I've also updated the screenshot up top for your reference.

**Review by Lapedra — APPROVED** [review]
Did you mean decrease padding? I just thought it was a lot of space above "get started..." If it's not that serious then I approve!

**Comment by Lapedra** [comment]
Great! I had to refresh. This looks good and I totally understand!

**Pull request merged**
